package de.maibornwolff.codecharta.importer.sourcecodeparser.oop.core.antlrinterop

enum class CodeTags: Tags {
    PACKAGE, IMPORT, METHOD, METHOD_CALL, CONDITION, ANNOTATION, ANNOTATION_INVOCATION, ANNOTATION_ELEMENT, INTERFACE_CONSTANT, CLASS_FIELD, CONSTRUCTOR, STATEMENT, EXPRESSION, VARIABLE, CLASS, INTERFACE, ENUM_CONSTANT, ENUM
}