import {
    invertColorRange,
    invertDeltaColors,
    setAmountOfEdgePreviews,
    setAmountOfTopLabels,
    setAreaMetric,
    setColorLabels,
    setColorMetric,
    setColorMode,
    setColorRange,
    setEdgeHeight,
    setEdgeMetric,
    setEnableFloorLabels,
    setGroupLabelCollisions,
    setHeightMetric,
    setHideFlatBuildings,
    setInvertArea,
    setInvertHeight,
    setIsWhiteBackground,
    setLabelMode,
    setLabelSize,
    setLabelsPerMap,
    setLayoutAlgorithm,
    setMapColors,
    setMargin,
    setScaling,
    setShowIncomingEdges,
    setShowMetricLabelNameValue,
    setShowMetricLabelNodeName,
    setShowOnlyBuildingsWithEdges,
    setShowOutgoingEdges
} from "../../../../mapState/mapState.write.facade"
import { setMaxTreeMapFiles } from "../../../../preferences/preferences.write.facade"
import {
    setAllFocusedNodes,
    focusNode,
    unfocusAllNodes,
    unfocusNode,
    setSearchPattern,
    setMarkedPackages,
    markPackages,
    unmarkPackage
} from "../../../../sharedView/sharedView.write.facade"
import { setState } from "../../../../store/state.actions"

export const actionsRequiringRerender = [
    setColorLabels,
    setMapColors,
    invertColorRange,
    invertDeltaColors,
    setShowMetricLabelNodeName,
    setShowMetricLabelNameValue,
    setIsWhiteBackground,
    setInvertArea,
    setInvertHeight,
    setHideFlatBuildings,
    setScaling,
    setEdgeHeight,
    setAmountOfEdgePreviews,
    setShowIncomingEdges,
    setShowOutgoingEdges,
    setAmountOfTopLabels,
    setLabelSize,
    setLayoutAlgorithm,
    setMaxTreeMapFiles,
    setColorMode,
    setEdgeMetric,
    setColorRange,
    setMargin,
    setSearchPattern,
    setAllFocusedNodes,
    focusNode,
    unfocusAllNodes,
    unfocusNode,
    setHeightMetric,
    setAreaMetric,
    setColorMetric,
    setShowOnlyBuildingsWithEdges,
    setMarkedPackages,
    markPackages,
    unmarkPackage,
    setEnableFloorLabels,
    setGroupLabelCollisions,
    setLabelsPerMap,
    setLabelMode,
    setState
]
