version: 2
updates:
- package-ecosystem: gradle
  directory: "/analysis"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/visualization"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
