version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/analysis/node-wrapper"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/analysis"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/visualization"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
