version: "3"
services:
    sonar:
        image: sonarqube:community
        container_name: sonar
        ports:
            - "9000:9000"
        volumes:
            - shared-volume:/mnt/data

    visualization:
        image: codecharta/codecharta-visualization
        container_name: codecharta-visualization
        ports:
            - "9001:80"
        volumes:
            - shared-volume:/mnt/data

    analysis:
        image: codecharta/codecharta-analysis
        container_name: codecharta-analysis
        volumes:
            - shared-volume:/mnt/data

volumes:
    shared-volume: {}
