#ifndef DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_DEFAULT_CREATURE_H
#define DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_DEFAULT_CREATURE_H

#include "creature.h"

extern const Creature DEFAULT_CREATURE;

#endif
