package de.maibornwolff.codecharta.analysers.analyserinterface.basefile

import de.maibornwolff.codecharta.model.Node
import de.maibornwolff.codecharta.model.NodeType
import de.maibornwolff.codecharta.serialization.ProjectDeserializer
import de.maibornwolff.codecharta.util.Logger
import java.io.File
import java.io.FileInputStream

open class BaseFileResolver {
    open fun loadBaseFileNodes(baseFile: File?): Map<String, Node> {
        if (baseFile == null) {
            return emptyMap()
        }

        if (!baseFile.exists()) {
            Logger.warn { "Base file '${baseFile.absolutePath}' does not exist, continuing with normal analysis... " }
            return emptyMap()
        }

        return try {
            val baseProject = ProjectDeserializer.deserializeProject(FileInputStream(baseFile))
            val nodeMap = mutableMapOf<String, Node>()
            extractFileNodesWithPaths(baseProject.rootNode, "", nodeMap)
            Logger.info { "Loaded ${nodeMap.size} file nodes from base file for checksum comparison" }
            nodeMap
        } catch (e: Exception) {
            Logger.warn { "Failed to load base file: ${e.message}" }
            emptyMap()
        }
    }

    private fun extractFileNodesWithPaths(node: Node, currentPath: String, nodeMap: MutableMap<String, Node>) {
        // Skip the root node name to match the relative paths generated by parsers
        val nodePath = if (currentPath.isEmpty() && node.name == "root") {
            ""
        } else if (currentPath.isEmpty()) {
            node.name
        } else {
            "$currentPath/${node.name}"
        }

        if (node.type == NodeType.File && node.checksum != null) {
            nodeMap[nodePath] = node
        }

        node.children.forEach { child ->
            extractFileNodesWithPaths(child, nodePath, nodeMap)
        }
    }
}
