#ifndef DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_CREATURE_TYPE_H
#define DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_CREATURE_TYPE_H

typedef enum CreatureType {
    CREATURE_TYPE_MONSTROSITY,
    CREATURE_TYPE_BEAST,
    CREATURE_TYPE_ABERRATION,
    CREATURE_TYPE_CELESTIAL,
    CREATURE_TYPE_DRAGON,
    CREATURE_TYPE_FIEND,
    CREATURE_TYPE_HUMANOID,
    CREATURE_TYPE_UNDEAD
} CreatureType;

#endif
