#ifndef DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_MOVEMENT_H
#define DE_SOTS_CELLARSANDCENTAURS_DOMAIN_MODEL_MOVEMENT_H

typedef enum SpeedType {
    SPEED_TYPE_WALKING,
    SPEED_TYPE_FLYING,
    SPEED_TYPE_SWIMMING,
    SPEED_TYPE_BURROWING,
    SPEED_TYPE_CLIMBING,
    SPEED_TYPE_COUNT
} SpeedType;

#endif
