#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/sh" ]; then
  exec "$basedir/sh"  "$basedir/node_modules/codecharta-analysis/public/bin/ccsh" "$@"
else 
  exec sh  "$basedir/node_modules/codecharta-analysis/public/bin/ccsh" "$@"
fi
