source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem "tzinfo-data"
gem "wdm", "~> 0.2.0" if Gem.win_platform?
gem "kramdown", ">= 2.3.1"
gem "activesupport", ">= 6.0.0.0"
gem "tzinfo", ">= 1.1"
gem "nokogiri", ">= 1.16.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "faraday-retry"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
