package de.maibornwolff.codecharta.importer.sourcecodeparser.oop.domain.tagging

enum class UnsortedCodeTags : CodeTags {
    ANY,

    PACKAGE, IMPORT, METHOD_CALL, ANNOTATION, ANNOTATION_INVOCATION, ANNOTATION_ELEMENT, RESOURCE, INTERFACE_CONSTANT, CLASS_FIELD, CONSTRUCTOR, STATEMENT, EXPRESSION, VARIABLE, CLASS, INTERFACE, ENUM_CONSTANT, ENUM, DEFAULT_CASE,

    FINALLY, THROWS_DECLARATION,
}