import {
    invertColorRange,
    invertDeltaColors,
    setAmountOfEdgePreviews,
    setAmountOfTopLabels,
    setColorLabels,
    setEdgeHeight,
    setEnableFloorLabels,
    setGroupLabelCollisions,
    setHideFlatBuildings,
    setInvertArea,
    setInvertHeight,
    setIsEdgeMetricVisible,
    setIsWhiteBackground,
    setLabelMode,
    setLabelSize,
    setLabelsPerMap,
    setMapColors,
    setScaling,
    setShowMetricLabelNameValue,
    setShowMetricLabelNodeName,
    setShowOnlyBuildingsWithEdges,
    toggleEdgeMetricVisible
} from "../../../mapState/mapState.facade"
// Transitional (Slice 10b structural): the pref leaf actions moved to preferences/store/ and are
// re-exported by the preferences facade until this grab-bag is deleted in the behavioral commit.
import {
    setScreenshotToClipboardEnabled,
    setExperimentalFeaturesEnabled,
    setIsColorMetricLinkedToHeightMetricAction,
    toggleIsColorMetricLinkedToHeightMetric,
    setPresentationMode,
    setMaxTreeMapFiles,
    setResetCameraIfNewFileIsLoaded,
    setSortingOrderAscending,
    toggleSortingOrderAscending
} from "../../../preferences/preferences.facade"
import { setLayoutAlgorithm } from "../../../mapState/store/layoutAlgorithm/layoutAlgorithm.actions"

export const appSettingsActions = [
    setColorLabels,
    setShowMetricLabelNodeName,
    setShowMetricLabelNameValue,
    setSortingOrderAscending,
    toggleSortingOrderAscending,
    setMapColors,
    invertColorRange,
    invertDeltaColors,
    setResetCameraIfNewFileIsLoaded,
    setShowOnlyBuildingsWithEdges,
    setIsEdgeMetricVisible,
    toggleEdgeMetricVisible,
    setIsWhiteBackground,
    setInvertHeight,
    setInvertArea,
    setHideFlatBuildings,
    setScaling,
    setEdgeHeight,
    setAmountOfEdgePreviews,
    setAmountOfTopLabels,
    setLabelSize,
    setPresentationMode,
    setExperimentalFeaturesEnabled,
    setScreenshotToClipboardEnabled,
    setLayoutAlgorithm,
    setMaxTreeMapFiles,
    setIsColorMetricLinkedToHeightMetricAction,
    toggleIsColorMetricLinkedToHeightMetric,
    setEnableFloorLabels,
    setLabelMode,
    setGroupLabelCollisions,
    setLabelsPerMap
]
