package de.maibornwolff.codecharta.importer.ooparser.antlrinterop

enum class CodeTags: Tags {
    PACKAGE, IMPORT, METHOD, METHOD_CALL, CONDITION, ANNOTATION, INTERFACE_CONSTANT, CLASS_FIELD, CONSTRUCTOR, STATEMENT, EXPRESSION, VARIABLE, CLASS, INTERFACE, ENUM_CONSTANT
}