#Code from https://github.com/upsidr/merge-gatekeeper
name: Merge Gatekeeper

on:
    pull_request:
        branches:
            - main

jobs:
    merge-gatekeeper:
        runs-on: ubuntu-latest
        permissions:
            checks: read
            statuses: read
        steps:
            -   name: Run Merge Gatekeeper
                  # NOTE: v1 is updated to reflect the latest v1.x.y. Please use any tag/branch that suits your needs:
                #       https://github.com/upsidr/merge-gatekeeper/tags
                #       https://github.com/upsidr/merge-gatekeeper/branches
                uses: upsidr/merge-gatekeeper@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    interval: 10
                    timeout: 1200
