name: Prepare a new Release (Visualization/Analysis)

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to release'
        required: true
        type: choice
        options:
          - visualization
          - analysis
      version_type:
        description: 'Version increment type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      prefix: ${{ steps.version.outputs.prefix }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update version and files
        id: version
        run: |
          set -e
          NEW_VERSION=$(bun run script/version-manager.ts ${{ inputs.repository }} ${{ inputs.version_type }})
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "prefix=${{ inputs.repository == 'visualization' && 'vis' || 'ana' }}" >> $GITHUB_OUTPUT

  commit:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Commit and tag changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Releasing ${{ needs.prepare.outputs.prefix }}-${{ needs.prepare.outputs.new_version }}"
          git tag "${{ needs.prepare.outputs.prefix }}-${{ needs.prepare.outputs.new_version }}"
          git push --follow-tags