name: Format Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
 check_prettier:
    name: Code Style
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
    - uses: actions/checkout@v5
    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Cache root node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-root-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install node
      run: |
        npm ci || (echo "npm ci failed, regenerating lock file and retrying..." && npm install --package-lock-only && npm ci)
      working-directory: ${{env.working-directory}}

    - name: Check formatting and linting
      run: |
        npm run format:check
      working-directory: ${{env.working-directory}}
